### PR TITLE
修复了管理权限

### PR DESCRIPTION
**Pull request by iozevo**

### CODE REVIEW

**Comment by Zenrac** [comment]
Hi, thanks for your PR, can you explain your change ?

**Comment by iozevo** [comment]
> Hi, thanks for your PR, can you explain your change?

你的语法是不清楚在那里，在说明

**Comment by Zenrac** [comment]
Can you answer in english ? I'm not talking Chinese ._.

**Comment by iozevo** [comment]
> Can you answer in english ? I'm not talking Chinese ._.

Sorry, your grammar and wording phrase was unclear. I am from china and I am an exchange student here in the US. If you need help on any Chinese phrasing let me know.

**Comment by Zenrac** [comment]
@iozevo Understood, thanks for your help. I'm not writing the Chienese translation myself. If you feel interessted about translating some lines someday, it'll be gladly accepted :)

**Pull request merged**
