### PR TITLE
Portuguese translation - lines 580 - 612

### PR DESCRIPTION
**Pull request by mluisas**

### CODE REVIEW

**Comment by Zenrac** [comment]
Thank you

**Comment by Zenrac** [comment]
@mluisas Just noticed that you forgot the following line : 

"music-shuffle-shuffled" : "Queue shuffled !",  

Can you gimme the translation / or open a PR ?

**Comment by mluisas** [comment]
Oh, sorry! The translation is: "Lista misturada!"

**Comment by Zenrac** [comment]
Thank 👍

**Pull request merged**
