### PR TITLE
Spanish_Translation_to_line_85

### PR DESCRIPTION
**Pull request by Jorege98**
I'll help too with the Catalan translation, but 1st we can work together to translate the spanish

### CODE REVIEW

**Comment by Zenrac** [comment]
Thanks, maybe it could be better if you use `usted` (basically the respectful form) instead of `tu` but I don't really know as I'm not speaking spanish.

Thank you again

**Comment by Zenrac** [comment]
I don't want it to look weird, the bot is supposed to talk to the user normally, so if you feel that `tu` is normal ignore my last comment

**Comment by Jorege98** [comment]
Tomorrow I'll check that, but I think it's well, I just will adapt to a "formal" form of Spanish

**Comment by Zenrac** [comment]
Thanks 👍

**Pull request merged**
